### ISSUE TITLE
404 error for figshare GitHub importer

### ISSUE THREAD

**Issue by davidjb** [mozillascience/code-research-object#20]
The URL of https://figshare.com/external/github/import (where the form leads to) is a 404, meaning this tool doesn't work.  Is this importer still available somewhere or is it gone for good?  

This tweet (https://twitter.com/jjmerelo/status/675380360696471553) is about the best info available that indicates they're changing to some form of web hooks.

Also, the current form action (https://github.com/mozillascience/code-research-object/blob/gh-pages/form/index.html#L26) is using HTTP when it should be HTTPS; submitting the form shows a security warning before eventually getting to the 404.

CC: @stevevandervalk

**Comment by hubgit** [comment]
I can't find any information about connecting a GitHub account or repository to figshare any more. We could perhaps replace the form and browser buttons with links to [Zenodo's GitHub connect page](https://zenodo.org/account/settings/github/)?

**Comment by davidjb** [comment]
Answering my own question, yes, the importer appears to be gone for good as it has been replaced by webhooks and OAuth (https://support.figshare.com/support/solutions/articles/6000150264-how-to-connect-figshare-with-your-github-account).  So this tool is probably best taken down.

As for Figshare, unfortunately GitHub's lack of granularity for permissions means that you need to give Figshare (or Zenodo, it's the same) the ability to admin webhooks for all your repos so it's not particularly friendly in that way.
